### ISSUE TITLE
Async API

### ISSUE THREAD

**Issue by brendonwm** [messagebird/csharp-rest-api#25]
It would be nice to have async versions of the client methods using HttpClient instead of HttpWebRequest. I don't think I'll have time to try and submit a pull request unfortunately.

**Comment by epels** [comment]
Hi @brendonwm, thanks for the suggestion!

Adding this to the client is not on the roadmap at this moment. Due to the synchronous nature of this library's internals, its performance would not benefit much from using async calls internally. From a user perspective, I would suggest wrapping calls in a task. E.g.:

```csharp
async Task<Balance> BalanceAsync()
{
    return Task.Run(() => client.Balance());
}

// ...

MessageBird.Objects.Balance balance = await BalanceAsync();
Console.WriteLine("{0}", balance);
```

If we decide to add this to the client, we will let you know! Thanks again for opening this issue.
