### ISSUE TITLE
Support for Verify HttpRequests Missing

### ISSUE THREAD

**Issue by stap123** [messagebird/csharp-rest-api#47]
Any chance of getting an implementation of the verify http request functionality added?

As per: https://developers.messagebird.com/docs/verify-http-requests

**Comment by stevenvolckaert** [comment]
I noticed the [RequestValidator](https://github.com/messagebird/csharp-rest-api/blob/master/MessageBird/RequestValidator.cs) class has been added recently, however it was added _after_ the latest available NuGet package, v3.1.0, was released.

Any chance on releasing a new NuGet package soon?

**Comment by ahmetkocadogan** [comment]
hey @stap123 @stevenvolckaert 

Required methods are available in the latest release, with the new request verification way via MessageBird-Signature-JWT header value. 

And the documentation is here : https://developers.messagebird.com/api/#verifying-http-requests

@stap123 you can close the issue if this issue is resolved for you.

**Comment by stevenvolckaert** [comment]
Hi @ahmetkocadogan, thank you very much for the new release!!
