### ISSUE TITLE
Support for SMS Status Reports Missing

### ISSUE THREAD

**Issue by stap123** [messagebird/csharp-rest-api#48]
The status reports are also not implemented, would be good to get this added too.

https://developers.messagebird.com/docs/sms-messaging#handle-a-status-report

**Comment by epels** [comment]
Hi @stap123, thanks for pointing out the status reports are not implemented in the client. How do you propose this be implemented?

**Comment by stap123** [comment]
Something relatively simple such as give a Request.Body stream to a method that would use Json.NET to deserialise the stream into a StatusReport object. 

You could then either build in automatic validation of the verify http request (https://developers.messagebird.com/docs/verify-http-requests) see #47 or add a method for calling to validate a status report object.

**Comment by epels** [comment]
Currently the SDK offers "client" operations: requests from this SDK to the MessageBird API. The great difference between that and the functionality proposed in this issue is that status reports are initiated by MessageBird.
An implication is that this requires your code to act as a server and accept incoming HTTP requests.

That being said: I think the parsing of these status reports should operate on built-in types (e.g. strings), and not on requests.
This way the functionality is available to anyone, regardless of what server-side framework they are using. It also has greater testability: no need to wire up fake HTTP requests. Another benefit is that it results in fewer (indirect) dependencies for our users.

What do you think? If anyone would like to pick this up: contributions/pull requests are more than welcome 🥇

**Comment by leej3691** [comment]
We need the simple functionality to get the status using the client, im not sure why there isnt just a method on the Messagebird.Client like client.GetStatusReport(string reference) and that just returns a status report object where we can get the status from that. Just like every other method you have on the API.
