### ISSUE TITLE
Sending File in WhatsApp Sandbox

### ISSUE THREAD

**Issue by ahmetkocadogan** [messagebird/csharp-rest-api#80]
I am sending a pdf file in whatsapp sandbox, but file is not received. And i got no error or exception while sending.

Is it a bug? Or whatsapp sandbox does not allow sending files?

Sending image and location is working.

**Comment by dandronic** [comment]
I think there is a problem with that specific pdf (or type). If I send another one (https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf) it works correctly, but the one you are sending it indeed does not get through).
I'll research to see if there are any known restrictions/issues with pdf files.
Can you do a test with sending https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf ?

**Comment by dandronic** [comment]
The file you are trying to send https://qconlondon.com/london-2017/system/files/presentation-slides/microsoft_bot_framework_best_practices.pdf is returning a data gzip compressed file/stream. This is something that MessageBird does not currently support (it will be added in the next weeks/months).
That's why it is failing. Host the file on a non gzip server and you should not have any more problems.

**Comment by ahmetkocadogan** [comment]
Thanks. I'll try your pdf file, and close the issue if it succeeds.

**Comment by ahmetkocadogan** [comment]
@dandronic  i sent the pdf file successfully. Thanks for clear explanation. I'am closing the issue.
